version: '3'

services:
    web-node-js:
        image: shounnnn/nodejs:latest
        ports:
            - "3000:3000"
        environment:
            - MONGODB_ADDON_URI=mongodb://mongodb:27017/test
        # networks:
        #     - demo-network
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        ports: 
            - "27017:27017"
        # networks:
        #     - demo-network

# networks:
#     demo-network:
#         driver: bridge
